# Configuration for automated dependency updates using Dependabot
version: 2
updates:
  # Define the target package ecosystem
  - package-ecosystem: "npm"
    # Specify the root directory
    directory: "/"
    # Schedule automated updates to run monthly
    schedule:
      interval: "monthly"
    # Labels to apply to Dependabot PRs
    labels:
      - "dependencies"
    # Specify the target branch for PRs
    target-branch: "develop"
    # Customize commit message prefix
    commit-message:
      prefix: "chore(deps):"
    # Limit parallel PRs and run at a quiet time
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"
      time: "05:00"
      timezone: "Etc/UTC"
    # Auto-request reviews (usernames or teams)
    reviewers:
      - "palisadoes"
    # Optional grouping to batch routine bumps
    groups:
      tooling:
        patterns:
          - "eslint*"
          - "prettier*"
          - "husky"
          - "lint-staged"
