# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"
early_access: false
chat:
  auto_reply: true
reviews:
  profile: "assertive"
  poem: false
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  request_changes_workflow: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - develop
      - develop-postgres
      - main
  path_filters:
    - '!**/docs/docs/**'
    - "!*.html"
    - "!*.md"
    - "!*.svg" 

