packages:
  - '.'

onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'
  - core-js
  - cypress
  - sharp

peerDependencyRules:
  allowedVersions:
    react: '>=16'
    react-dom: '>=16'

overrides:
  '@pdfme/common': '5.4.8'
  '@pdfme/schemas': '5.4.8'
  '@pdfme/generator': '5.4.8'
