services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_TALAWA_URL=${REACT_APP_TALAWA_URL:?Error: REACT_APP_TALAWA_URL is required}
    ports:
      - 4321:4321
    user: node
    healthcheck:
      test:
        ['CMD-SHELL', 'wget --spider -q http://localhost:4321/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
