contact_links:
    - name: 🤔 Questions and Help
      url: https://github.com/PalisadoesFoundation/talawa?tab=readme-ov-file#talawa
      about: This issue tracker is not for support questions. Please refer to the Slack community's help and discussion forums.
