contact_links:
    - name: 📃 Documentation Issue
      url: https://github.com/PalisadoesFoundation/talawa-docs/issues/new/choose
      about: This issue tracker is not for Documentation issues. Please file Documentation issues here.
    - name: 📃 Mobile Issue
      url: https://github.com/PalisadoesFoundation/talawa/issues/new/choose
      about: This issue tracker is not for Mobile issues. Please file Mobile issues here.
    - name: 📃 API Issue
      url: https://github.com/PalisadoesFoundation/talawa-api/issues/new/choose
      about: This issue tracker is not for API issues. Please file API issues here.
    - name: 🤔 Questions and Help
      url: https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-2e75w7ups-AVCObKnnHqNzd76CmIRyag
      about: This issue tracker is not for support questions. Please refer to the Slack community's help and discussion forums.
