# Step 1: Build Stage
FROM node:23.7.0 AS builder
WORKDIR /talawa-admin

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=production

RUN npm run build

# Step 2: Production Stage
FROM node:23.7.0-alpine AS production
WORKDIR /talawa-admin

COPY --from=builder /talawa-admin /talawa-admin

ENV NODE_ENV=production

EXPOSE 4321
CMD ["npm", "run", "serve"]
