FROM node:24 AS build

ARG PORT=4321
ENV PORT=${PORT}

WORKDIR /usr/src/app

COPY package*.json ./
RUN corepack enable && corepack prepare pnpm@10.4.1 --activate && pnpm install

COPY . .

RUN pnpm run build
EXPOSE ${PORT}

CMD ["pnpm", "run", "serve"]