name: Running Cypress Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  Install:
    runs-on: ubuntu-latest
    env:
        REACT_APP_TALAWA_URL: http://localhost:4000/graphql
    steps:
      - name: Checkout 
        uses: actions/checkout@v4 

      - name: Cypress Install 
        uses: cypress-io/github-action@v6
        with:
            runTests: false
            build: npm run build

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: build
            if-no-files-found: error
            path: build
            retention-days: 1

  Setup-Backend-Run-Tests: 
    if: github.repository == 'palisadoesFoundation/talawa-admin'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: Install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v4
        with:
            path: talawa-admin

      - name: Checkout Backend Repo
        uses: actions/checkout@v4
        with:
            repository: palisadoesFoundation/talawa-api
            ref: develop
            path: talawa-api

      - name: Install Devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Copy devcontainer environment file
        run: cp talawa-api/envFiles/.env.devcontainer talawa-api/.env

      - name: Bring up devcontainer
        run: |
          cd talawa-api
          devcontainer up --workspace-folder .

      - name: Wait for Devcontainer to be ready
        run: |
          echo "Waiting for devcontainer services to be ready..."
          sleep 10

      - name: Verify Running Containers
        run: docker ps

      - name: Get container name
        id: container
        run: |
          CONTAINER_NAME=$(docker ps --format "table {{.Names}}" | grep -E "(talawa-api|api)" | head -1)
          echo "container_name=$CONTAINER_NAME" >> $GITHUB_OUTPUT
          echo "Found container: $CONTAINER_NAME"

      - name: Install dependencies inside the container
        run: docker exec ${{ steps.container.outputs.container_name }} /bin/bash -c 'pnpm install'

      - name: Start server and monitor logs
        run: |
          docker exec ${{ steps.container.outputs.container_name }} /bin/bash -c 'pnpm run start_development_server' &
          sleep 10

      - name: Wait for GraphQL endpoint to become available
        if: always()
        run: |
          echo "Waiting for the GraphQL endpoint to become available..."
          CONTAINER_NAME=${{ steps.container.outputs.container_name }}
          for i in {1..60}; do
            # Check if container exists first
            if ! docker ps | grep -q "$CONTAINER_NAME"; then
              echo "Container $CONTAINER_NAME not found. Waiting..."
              sleep 2
              continue
            fi
            docker exec $CONTAINER_NAME which curl >/dev/null 2>&1 || {
              docker exec $CONTAINER_NAME apt-get update && docker exec $CONTAINER_NAME apt-get install -y curl
            }
            RESPONSE=$(docker exec $CONTAINER_NAME curl -s -X POST http://127.0.0.1:4000/graphql -H "Content-Type: application/json" -d '{"query":"{__typename}"}' 2>/dev/null || echo "Connection failed")
            if echo "$RESPONSE" | grep -q '__typename'; then
              echo "GraphQL endpoint is available!"
              exit 0
            fi
            echo "GraphQL endpoint not ready. Retrying in 2 seconds..."
            sleep 2
          done
          echo "GraphQL endpoint did not become available within the expected time."
          exit 1 

      - name: Determine PR Origin
        id: pr_origin
        run: |
          echo "is_forked=$(echo ${{ github.event.pull_request.head.repo.fork }})" >> $GITHUB_OUTPUT

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: talawa-admin/build
          merge-multiple: true     

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: talawa-admin
          start: npm run serve
          wait-on: 'http://localhost:4321'
          wait-on-timeout: 300
          config-file: cypress.config.ts
          parallel: true
          group: 'UI Tests - Container ${{ matrix.containers }}'
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Cleanup:
    if: always() && github.repository == 'palisadoesFoundation/talawa-admin'
    needs: Setup-Backend-Run-Tests
    runs-on: ubuntu-latest
    steps:
      - name: Delete build artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: build