name: Running Cypress Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  Install:
    runs-on: ubuntu-latest
    env:
      REACT_APP_TALAWA_URL: http://localhost:4000/graphql
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Build Frontend
        run: npm run build

      - name: Save Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          retention-days: 1

  Setup-Backend-Run-Tests:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    needs: Install
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4
        with:
          repository: palisadoesFoundation/talawa-api
          ref: develop

      - name: Setup Devcontainer
        run: |
          npm install -g @devcontainers/cli
          cp envFiles/.env.devcontainer .env
          devcontainer up --workspace-folder .

      - name: Install Dependencies
        run: docker exec talawa-api-1 /bin/bash -c 'pnpm install'

      - name: Start Backend Server
        run: docker exec talawa-api-1 /bin/bash -c 'pnpm run start_development_server &'

      - name: Verify Backend Health
        run: |
          docker exec talawa-api-1 /bin/bash -c 'apt-get update && apt-get install -y curl'
          
          for i in {1..30}; do
            if docker exec talawa-api-1 /bin/bash -c 'curl -s http://localhost:4000/graphql -d ''{"query":"{__typename}"}''' | grep -q __typename; then
              echo "Backend ready!"
              exit 0
            fi
            sleep 2
          done
          echo "Backend failed to start"
          exit 1

      - name: Get Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: frontend-build

      - name: Serve Frontend & Run Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend-build
          start: npx serve -s -l 4321 .
          wait-on: 'http://localhost:4321'
          config-file: cypress.config.ts
        env:
          CYPRESS_BASE_URL: http://localhost:4321
          REACT_APP_TALAWA_URL: http://localhost:4000/graphql

  Cleanup:
    if: always()
    runs-on: ubuntu-latest
    needs: [Install, Setup-Backend-Run-Tests]
    steps:
      - name: Remove Artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: build